[[_client_registration_tool]]
== Client Registration Tool

`Client Registration Tool` is a command line interface (CLI) tool that can be used by application developers to configure new clients
to integrate with {book_project_name}. It is specifically designed to interact with {{book.project.name}} Client Registration REST endpoints.

To allow a particular user to use the tool a {book_project_name} administrator will typically use `Admin Console` to configure
 a new user, or configure a new client, and a client secret.


[[_configure_user_for_reg_cli]]
=== Configuring a new regular user for use with Registration Client Tool

Login as `admin` into `Admin Console` (e.g. `http://localhost:8080/auth/admin`). Select a realm you want to administer.
If you want to use existing user, select it for edit, otherwise create a new user. Go to `Role Mappings` tab. Under
`Client Roles` select `realm-management`. Under `Available Roles` select `manage-client` for full set of client management
permissions. Alternatively you can choose `view-clients` for read-only or `create-client` for ability to create new clients.
These permissions grant user the capability to perform operations without the use of `Initial Access Token` or
`Registration Access Token`.

It's possible to not assign users any of `realm-management` roles. In that case user can still login with `Registration Client Tool`
but will not be able to use it without having possession of an `Initial Access Token`. Trying to perform any operations
without it will result in `403 Forbidden` error.

Administrator can issue `Initial Access Tokens` from `Admin Console` by selecting `Initial Access Token` tab under `Realm Settings`.


=== Configuring a client for use with Registration Client Tool

By default the `Registration Client Tool` uses `admin-cli` client which is automatically configured for every new realm.
No additional client configuration is required when using login with a username. You may wish to firm up security by
configuring the client `Access Type` as `Confidential`, and under `Credentials` tab select `ClientId and Secret`. When
running `kcreg login` you then also have to provide a secret e.g. by using `--secret`.

If you want to use a separate client configuration for `Registration Client Tool` then you can create a new client - for
example you can call it `reg-cli`. When running `kcreg login` you then need to specify a `clientId` to use e.g. `-c reg-cli`.

If you want to use a service account associated with the client, then you need to enable a service account. In `Admin Client`
you go to `Clients` section, and select a client for edit. Then under `Settings` first change `Access Type` to `Confidential`.
Then toggle `Service Accounts Enabled` setting to `On`, and `Save` the configuration.

Under `Credentials` tab you can choose to configure either `Client Id and Secret`, or `Signed JWT`.

You can now avoid specifying user when using `kcreg login` and only provide a client secret or keystore info.

=== Installing Client Registration Tool

Change to the directory where you want to install the client.

Unzip the downloaded distribution:

[source,bash]
----
$ unzip keycloak-client-tools-*.zip
----

Add the directory to your PATH:

[source,bash]
----
$ export PATH=$PATH:$PWD/keycloak-client-tools
----

Make sure the client works:

[source,bash]
----
$ kcreg help
----


=== Using Client Registration Tool

Usually a user will first start an authenticated session by logging in, then perform some CRUD operations, and possibly
finish the session by logging out.

For example:

[source,bash]
----
$ kcreg login -s http://localhost:8080/auth -r demo -c reg-cli --secret $CLIENT_SECRET
$ kcreg create -s clientId=my_client -s 'redirectUris=["http://localhost:8980/myapp/*"]' -t $INITIAL_ACCESS_TOKEN
----

==== Logging In

When logging in with `Client Registration Tool` you specify a server endpoint url, and a realm. Then you specify a username,
or alternatively you can only specify a client id, which will result in special service account being used. In the first case,
a password for the specified user has to be used at login. In the latter case there is no user password - only client secret
or a `Signed JWT` is used.

Regardless of the method, the account that logs in needs to have proper permissions in order to be able to perform client
registration operations. Keep in mind that any account can only have permissions to manage clients within the same realm.
If you need to manage different realms, you need to configure users in different realms with permissions to manage clients.

`Client Registration Tool` by itself does not support configuring the users, for that you would need to use `Admin Console`
web interface or `Admin Client Tool` once it's available.

For more information on using the tool see integrated help:

[source,bash]
----
$ kcreg help
$ kcreg help login
$ kcreg help create
----

Here are some examples of logging in.

Login into default server (`http://localhost:8080/auth`) as user `admin` of `master` realm. You will be prompted for password.

[source,bash]
----
$ kcreg login -r master -u admin
----

Login into `http://localhost:9080/auth` as user `admin` of `master` realm, passing a password via a standard input.

[source,bash]
----
$ kcreg login -s http://localhost:9080/auth -r master -u admin << EOF
mypassword
EOF
----

Login as user `admin` of `master` realm, using env variable PASSWORD as a password:

[source,bash]
----
$ kcreg login -r master -u admin -p $PASSWORD
----

Login using a service account for client `reg-cli`. You will be prompted for client secret:

[source,bash]
----
$ kcreg login -r master -c reg-cli
----

Login as user `admin` of `master` realm, and authenticating the default client (admin-cli) with a secret.
You will be prompted for a user password, and for a client secret:

[source,bash]
----
$ kcreg login -r master -u admin --secret -
----

Login using a service account for client `reg-cli`, authenticating the client with a signed JWT. You will be prompted for a keystore password, and a key password. Alias `reg-cli` will be used to retrieve the key:

[source,bash]
----
$ kcreg login -r master -c reg-cli -k ~/.keycloak/keystore.jks
----

Login using `user` username, and a client with client id `reg-cli`, authenticating the client with signed JWT. You will be prompted for a user password to authenticate user, and store and key passwords to authenticate the client:

[source,bash]
----
$ kcreg login -r master -u user -c reg-cli -k ~/.keycloak/keystore.jks
----


When client tool successfully logs in it receives authorization tokens and saves them into a private config file so they can be used for subsequent invocations. By default the location of this file is $HOME/.keycloak/kcreg.cache, but can be overridden when invoking kcreg tool - e.g. `kcreg -c /tmp/.kcreg_server1.conf` create ...



==== Creating a new client
TODO

==== Getting existing client config
TODO

==== Updating a client
TODO

==== Deleting a client
TODO

==== Updating a registration access token
TODO




=== Troubleshooting

* Q: When logging in I get an error: `Parameter client_assertion_type is missing [invalid_client]`
+
A: Your client is configured with `Signed JWT` token credentials which means you have to use `-k`, `--keystore` parameter when logging in.
